# Generated by Django 4.2.11 on 2024-04-03 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfolio',
            name='transcription',
            field=ckeditor.fields.RichTextField(blank=True, help_text='<br><br>Lines of text:<br>\nTo start creating lines of text click the \'numbered list\' button\n<br>\nTo manually override an automatic line number simply:\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;1. Click the \'Source\' button\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;2. Add a value to the <em>&lt;li&gt;</em>. E.g. change <em>&lt;li&gt;</em> to <em>&lt;li value="4"&gt;</em>\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;3. If last line is a range (e.g. 8-9) add <em>\'data-range-end\'</em>. E.g. <em>&lt;li data-range-end="9"&gt;</em>\n<br>\n<br>\nTables:\n<br>\nTo add a table, click on the table button in the toolbar\n<br>\nYou can edit/delete an existing table (e.g. add/remove a row/column) by right clicking the table and choosing the appropriate option\n<br>\nIf you add a new list of line numbers below a table, please note that you\'ll need to set the line number by adding the value attribute to the first <em>&lt;li&gt;</em> as described above (e.g. <em>&lt;li value="4"&gt;</em>)\n<br>\n<br>\nHeadings:\n<br>\nTo add a heading in between lists you must ensure the text is marked as a \'Heading 1\' either by:\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;1. Using the \'Format\' button in the toolbar to select Heading 1\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;2. Clicking the \'Source\' button and adding the manual HTML like so: <em>&lt;h1&gt;Heading Text Here&lt;/h1&gt;</em>\n<br>\nPlease note that the heading text must appear outside of a list and not as a numbered item in a list, otherwise it will be duplicated on the public interface.\n', null=True),
        ),
        migrations.AlterField(
            model_name='textfolio',
            name='translation',
            field=ckeditor.fields.RichTextField(blank=True, help_text='<br><br>Lines of text:<br>\nTo start creating lines of text click the \'numbered list\' button\n<br>\nTo manually override an automatic line number simply:\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;1. Click the \'Source\' button\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;2. Add a value to the <em>&lt;li&gt;</em>. E.g. change <em>&lt;li&gt;</em> to <em>&lt;li value="4"&gt;</em>\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;3. If last line is a range (e.g. 8-9) add <em>\'data-range-end\'</em>. E.g. <em>&lt;li data-range-end="9"&gt;</em>\n<br>\n<br>\nTables:\n<br>\nTo add a table, click on the table button in the toolbar\n<br>\nYou can edit/delete an existing table (e.g. add/remove a row/column) by right clicking the table and choosing the appropriate option\n<br>\nIf you add a new list of line numbers below a table, please note that you\'ll need to set the line number by adding the value attribute to the first <em>&lt;li&gt;</em> as described above (e.g. <em>&lt;li value="4"&gt;</em>)\n<br>\n<br>\nHeadings:\n<br>\nTo add a heading in between lists you must ensure the text is marked as a \'Heading 1\' either by:\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;1. Using the \'Format\' button in the toolbar to select Heading 1\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;2. Clicking the \'Source\' button and adding the manual HTML like so: <em>&lt;h1&gt;Heading Text Here&lt;/h1&gt;</em>\n<br>\nPlease note that the heading text must appear outside of a list and not as a numbered item in a list, otherwise it will be duplicated on the public interface.\n', null=True),
        ),
    ]
