# Generated by Django 4.2.11 on 2024-05-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_alter_textfolio_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfolio',
            name='image_hide',
            field=models.BooleanField(default=False, help_text="e.g. if you don't have permission to share the image publicly", verbose_name='Hide image on public website'),
        ),
    ]
