# Generated by Django 4.2.14 on 2024-07-31 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_textfolio_image_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlTextSourceOfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('name_unidecode', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name_unidecode'), 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='text',
            name='image_credit_custom',
            field=models.CharField(blank=True, help_text="Images are credited to the collection by default. If you'd like to credit them to someone else, provide their name here.", max_length=1000, null=True, verbose_name='image credit (custom)'),
        ),
        migrations.AddField(
            model_name='textrelatedpublication',
            name='details',
            field=models.CharField(blank=True, help_text='Provide additional details, such as "The IEDC translation and transcription have been taken from this publication".', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='admin_source_of_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='texts', to='corpus.sltextsourceofdata', verbose_name='source of data'),
        ),
    ]
