# Generated by Django 4.2.22 on 2025-07-14 18:25

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='codex_images_location',
            field=models.TextField(blank=True, help_text="\n        Include either a link to a IIIF manifest (if using IIIF images) OR the name of the directory on the server (if using local images).\n        <br>A IIIF manifest URL must start with 'https://' and include '/iiif/' in it.\n        <br>Examples of valid IIIF manifest URLs include:\n        <br>- https://iiif.bodleian.ox.ac.uk/iiif/manifest/8287e6c8-8b65-4a55-8ad0-e22dff4eccc2.json\n        <br>- https://cudl.lib.cam.ac.uk//iiif/MS-BROWNE-K-00001", null=True),
        ),
        migrations.AddField(
            model_name='textfolio',
            name='palaeography',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='<br>Optional. Only relevant to some texts.', null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='commentary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='<br>Commentary will not be displayed on the public website. It is for internal project team purposes only.', null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='texts', to='corpus.sltextcorpus', verbose_name='Findspots'),
        ),
        migrations.AlterField(
            model_name='text',
            name='summary_of_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfolio',
            name='transcription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='<br><br>Lines of text:<br>\nTo start creating lines of text click the \'numbered list\' button\n<br>\nTo manually override an automatic line number simply:\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;1. Click the \'Source\' button\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;2. Add a value to the <em>&lt;li&gt;</em>. E.g. change <em>&lt;li&gt;</em> to <em>&lt;li value="4"&gt;</em>\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;3. If last line is a range (e.g. 8-9) add <em>\'data-range-end\'</em>. E.g. <em>&lt;li data-range-end="9"&gt;</em>\n<br>\n<br>\nTables:\n<br>\nTo add a table, click on the table button in the toolbar\n<br>\nYou can edit/delete an existing table (e.g. add/remove a row/column) by right clicking the table and choosing the appropriate option\n<br>\nIf you add a new list of line numbers below a table, please note that you\'ll need to set the line number by adding the value attribute to the first <em>&lt;li&gt;</em> as described above (e.g. <em>&lt;li value="4"&gt;</em>)\n<br>\n<br>\nHeadings:\n<br>\nTo add a heading in between lists you must ensure the text is marked as a \'Heading 1\' either by:\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;1. Using the \'Format\' button in the toolbar to select Heading 1\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;2. Clicking the \'Source\' button and adding the manual HTML like so: <em>&lt;h1&gt;Heading Text Here&lt;/h1&gt;</em>\n<br>\nPlease note that the heading text must appear outside of a list and not as a numbered item in a list, otherwise it will be duplicated on the public interface.\n', null=True),
        ),
        migrations.AlterField(
            model_name='textfolio',
            name='translation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='<br><br>Lines of text:<br>\nTo start creating lines of text click the \'numbered list\' button\n<br>\nTo manually override an automatic line number simply:\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;1. Click the \'Source\' button\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;2. Add a value to the <em>&lt;li&gt;</em>. E.g. change <em>&lt;li&gt;</em> to <em>&lt;li value="4"&gt;</em>\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;3. If last line is a range (e.g. 8-9) add <em>\'data-range-end\'</em>. E.g. <em>&lt;li data-range-end="9"&gt;</em>\n<br>\n<br>\nTables:\n<br>\nTo add a table, click on the table button in the toolbar\n<br>\nYou can edit/delete an existing table (e.g. add/remove a row/column) by right clicking the table and choosing the appropriate option\n<br>\nIf you add a new list of line numbers below a table, please note that you\'ll need to set the line number by adding the value attribute to the first <em>&lt;li&gt;</em> as described above (e.g. <em>&lt;li value="4"&gt;</em>)\n<br>\n<br>\nHeadings:\n<br>\nTo add a heading in between lists you must ensure the text is marked as a \'Heading 1\' either by:\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;1. Using the \'Format\' button in the toolbar to select Heading 1\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;2. Clicking the \'Source\' button and adding the manual HTML like so: <em>&lt;h1&gt;Heading Text Here&lt;/h1&gt;</em>\n<br>\nPlease note that the heading text must appear outside of a list and not as a numbered item in a list, otherwise it will be duplicated on the public interface.\n', null=True),
        ),
        migrations.AlterField(
            model_name='textfolio',
            name='transliteration',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='<br>Optional. Only relevant to some Middle Persian texts.', null=True),
        ),
    ]
