# Generated by Django 4.2.22 on 2025-07-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_text_codex_images_location_textfolio_palaeography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='texts', to='corpus.sltextcorpus', verbose_name='Groups'),
        ),
    ]
