# Generated by Django 5.2.7 on 2025-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_alter_text_corpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='admin_principal_editor_details',
            field=models.CharField(blank=True, help_text='Optional. Include any necessary additional details about the Principal Editor of this text.', max_length=1000, null=True, verbose_name='principal editor (details)'),
        ),
    ]
