# Generated by Django 5.2.10 on 2026-02-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0009_text_admin_principal_editor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='gregorian_date_sort',
            field=models.CharField(blank=True, help_text='Used for sorting results by date on public website', max_length=1000, null=True),
        ),
    ]
