# Generated by Django 4.2.1 on 2023-06-03 20:48

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_data_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': [django.db.models.functions.text.Upper('email'), 'id']},
        ),
    ]
